name: postfix-macros

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, beta, 1.42.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run cargo check --all
      run: |
        cargo check --all
    - name: Run the tests
      if: matrix.toolchain != '1.42.0'
      run: |
        RUSTFLAGS="-D warnings" cargo test --all
    - name: Run cargo doc
      run: |
        cargo doc --all
